update dapp to use new sdk signatures
rsksmart/rif-relay-sample-dapp pull request #19
Opened 2022-06-08 17:30 UTC by ironFe93

2022-06-08 19:02 UTC, antomor requested changes
I haven't tested it yet, but it looks good to me for now. I've just left a couple of doubts, but I'd prefer to test it before approving.

2022-06-08 19:02 UTC, antomor commented on src/App.tsx
> +            const relayingServices = new DefaultRelayingServices(web3);
👍🏼

2022-06-08 19:02 UTC, antomor commented on src/components/Footer.tsx
> +            return swWithBalance as SmartWalletWithBalance;
why don't we define the type when we declare the variable at line 39?

2022-06-09 13:02 UTC, ironFe93 commented on src/components/Footer.tsx
> +            return swWithBalance as SmartWalletWithBalance;
I had some issues with this. Basically in order to make this work, I would have to add the properties "balance" and "rbtcBalance" to the sdk interface for the smart wallet.

2022-06-13 08:29 UTC, antomor commented
@ironFe93 it looks like CI is failing because of `prettier`. Could you please have a look at it?

2022-06-17 14:29 UTC, merged